/* eslint-disable @typescript-eslint/no-explicit-any */
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Building2, Database, HardHat, ReceiptText } from "lucide-react";
import { Panel, StatCard, prospectDb } from "@/components/prospect-hub/shared";
export default function SupplierIntelligence(){
 const q=useQuery({queryKey:["supplier-intelligence"],queryFn:async()=>{const [p,profiles,grades,payments]=await Promise.all([
 prospectDb.from("prospects").select("id,company_name,registration_number,province,city,procurement_record_count,total_award_value,email,phone").gt("procurement_record_count",0).order("total_award_value",{ascending:false}),
 prospectDb.from("prospect_supplier_profiles").select("*"),prospectDb.from("prospect_cidb_grades").select("*"),prospectDb.from("prospect_supplier_payments").select("*")]);for(const r of [p,profiles,grades,payments])if(r.error)throw r.error;return{prospects:p.data??[],profiles:profiles.data??[],grades:grades.data??[],payments:payments.data??[]}}});
 const d=q.data;const profiles=new Map((d?.profiles??[]).map((x:any)=>[x.prospect_id,x]));const grades=new Map<string,any[]>();for(const g of d?.grades??[]){const a=grades.get(g.prospect_id)||[];a.push(g);grades.set(g.prospect_id,a)}const paid=new Map<string,number>();for(const x of d?.payments??[])paid.set(x.prospect_id,(paid.get(x.prospect_id)||0)+Number(x.amount||0));
 return <div className="space-y-5"><div><h2 className="text-xl font-semibold">Supplier Intelligence</h2><p className="text-sm text-muted-foreground">Supplier 360 combines procurement history with source-attributed CIDB, authorised/public-derived CSD and Treasury data.</p></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Procurement suppliers" value={d?.prospects.length??"…"} icon={Building2}/><StatCard label="CIDB matched" value={(d?.profiles??[]).filter((x:any)=>x.cidb_crs_number).length} icon={HardHat}/><StatCard label="CSD identified" value={(d?.profiles??[]).filter((x:any)=>x.csd_supplier_number).length} icon={Database}/><StatCard label="Payment records" value={d?.payments.length??0} icon={ReceiptText}/></div>
 <Panel title="Supplier 360" description="CIDB/CSD/payment fields appear only when supported by the stated source."><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="text-left text-xs text-muted-foreground"><tr><th className="py-2">Supplier</th><th>CSD</th><th>CIDB</th><th>Grades</th><th>Location</th><th>Awards</th><th>Public payments</th><th>Contact</th><th>Quality</th></tr></thead><tbody>{(d?.prospects??[]).map((p:any)=>{const sp:any=profiles.get(p.id);const gs=grades.get(p.id)||[];return <tr key={p.id} className="border-t align-top"><td className="py-3 pr-3"><Link className="font-medium text-primary hover:underline" to={"../prospects/"+p.id}>{p.company_name}</Link><p className="text-xs text-muted-foreground">{p.registration_number||"Registration not captured"}</p></td><td className="pr-3">{sp?.csd_supplier_number||"—"}</td><td className="pr-3">{sp?.cidb_crs_number||"—"}</td><td className="pr-3">{gs.length?gs.map((g:any)=>String(g.grade||"")+g.class_code).join(", "):"—"}</td><td className="pr-3">{[p.city,p.province].filter(Boolean).join(", ")||"—"}</td><td className="pr-3">{p.procurement_record_count||0}<p className="text-xs text-muted-foreground">{p.total_award_value?"R "+Number(p.total_award_value).toLocaleString("en-ZA"):""}</p></td><td className="pr-3">{paid.has(p.id)?"R "+Number(paid.get(p.id)).toLocaleString("en-ZA"):"—"}</td><td className="pr-3">{p.email||p.phone||"Needs enrichment"}</td><td>{sp?.data_quality_score??0}%</td></tr>})}</tbody></table></div></Panel>
 <div className="grid gap-4 md:grid-cols-3"><Panel title="CIDB" description="Public contractor-register intelligence."><p className="text-sm text-muted-foreground">CRS, status, enterprise/trading details, classes of works, grades, expiry, B-BBEE and Potentially Emerging status.</p></Panel><Panel title="CSD" description="Authorised or legitimately public-derived data only."><p className="text-sm text-muted-foreground">MAAA/CSD identifier, supplier verification, commodities, delivery locations, classifications, accreditations and verification indicators.</p></Panel><Panel title="Treasury payments" description="Public procurement/payment intelligence."><p className="text-sm text-muted-foreground">Government customer, payment date/value, contract references and procurement category where publicly available. Payment history is not tax-compliance evidence.</p></Panel></div></div>;
}