/* eslint-disable @typescript-eslint/no-explicit-any */
import { useMemo } from "react";
import { useSearchParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { prospectDb } from "@/components/prospect-hub/shared";
const labels:Record<string,string>={all:"All opportunities",court:"Court judgments",debt:"SARS debt & enforcement",vat_paye:"VAT & PAYE cases",disputes:"Tax disputes / appeals",s163:"s163 preservation orders",s164:"s164 suspension of payment",s200:"s200 compromise",liquidation:"Liquidation & insolvency",business_rescue:"Business rescue",review:"Review queue",leads:"Qualified / contact-ready"};
const map:Record<string,string[]>={court:["sars_debt_enforcement","preservation_order","vat","paye","tax_dispute_appeal","s164_suspension","s200_compromise","other_tax"],debt:["sars_debt_enforcement"],vat_paye:["vat","paye"],disputes:["tax_dispute_appeal"],s163:["preservation_order"],s164:["s164_suspension"],s200:["s200_compromise"],liquidation:["liquidation","insolvency"],business_rescue:["business_rescue"]};
const pretty=(s:string)=>s.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function SarsOpportunityList(){
 const [params]=useSearchParams(); const view=params.get("view")||"all";
 const q=useQuery({queryKey:["sars-opportunities",view],queryFn:async()=>{const r=await prospectDb.from("sars_opportunities").select("*,prospects(id,company_name,email,phone,website,province,sector),prospect_public_signals(title,signal_type,signal_date,case_number,court_or_authority,source_url,evidence_summary)").order("score",{ascending:false});if(r.error)throw r.error;return r.data??[]}});
 const rows=useMemo(()=>{let x=q.data??[];if(map[view])x=x.filter((r:any)=>map[view].includes(r.opportunity_type));if(view==="review")x=x.filter((r:any)=>r.status==="review");if(view==="leads")x=x.filter((r:any)=>["qualified","contact_ready","contacted","follow_up","converted"].includes(r.status));return x},[q.data,view]);
 return <div className="space-y-4"><div><h2 className="text-xl font-semibold">{labels[view]||"SARS opportunities"}</h2><p className="text-sm text-muted-foreground">{rows.length} opportunities. Every classification remains tied to its public evidence.</p></div>
 <div className="overflow-x-auto rounded-2xl border bg-card"><table className="w-full min-w-[1000px] text-sm"><thead className="bg-muted/40 text-left text-xs text-muted-foreground"><tr><th className="p-3">Company</th><th>Opportunity</th><th>Score</th><th>Status</th><th>Documented issue</th><th>Contact</th><th>Source</th></tr></thead><tbody>
 {rows.map((r:any)=><tr key={r.id} className="border-t align-top"><td className="p-3 font-medium">{r.prospects?.company_name}</td><td className="p-3">{pretty(r.opportunity_type)}</td><td className="p-3 font-semibold">{r.score}</td><td className="p-3 capitalize">{r.status.replace(/_/g," ")}</td><td className="max-w-md p-3"><p>{r.prospect_public_signals?.evidence_summary||r.issue_summary||"—"}</p><p className="mt-1 text-xs text-muted-foreground">{[r.prospect_public_signals?.court_or_authority,r.prospect_public_signals?.case_number,r.prospect_public_signals?.signal_date].filter(Boolean).join(" · ")}</p></td><td className="p-3 text-xs">{r.prospects?.email||r.prospects?.phone||"Needs enrichment"}</td><td className="p-3">{r.prospect_public_signals?.source_url?<a className="text-primary underline" target="_blank" rel="noreferrer" href={r.prospect_public_signals.source_url}>Evidence</a>:"—"}</td></tr>)}
 {!rows.length?<tr><td className="p-8 text-center text-muted-foreground" colSpan={7}>No opportunities in this category yet. Historical discovery continues automatically.</td></tr>:null}
 </tbody></table></div></div>;
}